# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Answer
tagline:          'When you work hard, every good things happen.'
description:      ''
url:              https://gavincyi.github.io/
baseurl:          /

author:
  name:           'Gavin Chan'
  url:            https://github.com/gavincyi

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/gavincyi
